# Generated by Django 3.1.6 on 2021-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0002_auto_20210221_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.CharField(max_length=100, verbose_name='Фото')),
                ('dateBirth', models.DateField(verbose_name='Дата рождения')),
                ('dateStartJob', models.DateField(verbose_name='Дата приема на работу')),
                ('description', models.TextField(verbose_name='Описание')),
                ('note', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
