# Generated by Django 3.1.6 on 2021-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0003_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='dateBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='dateStartJob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
