# Generated by Django 3.1.6 on 2021-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0007_auto_20210227_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.IntegerField(max_length=10, verbose_name='Телефон')),
                ('days', models.CharField(choices=[(None, 'Выберете удобное для Вас время'), ('1', 'пн-пт утро'), ('2', 'пн-пт вечер'), ('3', 'сб-вс утро'), ('4', 'сб-вс день')], default=None, max_length=30, verbose_name='Дни')),
                ('textMessage', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('date_in', models.DateField(auto_now=True, null=True, verbose_name='Дата')),
                ('time_in', models.TimeField(auto_now=True, null=True, verbose_name='Время')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Пробная тренировка',
                'verbose_name_plural': 'Пробные тренировки',
            },
        ),
        migrations.AlterField(
            model_name='cards',
            name='number_card',
            field=models.PositiveIntegerField(verbose_name='Номер карты'),
        ),
    ]
