# Generated by Django 3.1.6 on 2021-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0008_auto_20210302_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='status',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number_card',
            field=models.CharField(max_length=15, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='textMessage',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
